name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

env:
  AWS_REGION: us-east-1
  APPLICATION_NAME: full-cicd
  STACK_NAME: full-cicd-infrastructure

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      # Upload source files to share between jobs
      - name: Upload source files
        uses: actions/upload-artifact@v4
        with:
          name: source-files
          path: |
            package.json
            package-lock.json
            server.js
            public/
          retention-days: 1

  deploy-infrastructure:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    outputs:
      s3-bucket: ${{ steps.stack-outputs.outputs.s3-bucket }}
      application-name: ${{ steps.stack-outputs.outputs.application-name }}
      environment-name: ${{ steps.stack-outputs.outputs.environment-name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file cloudformation/infrastructure.yml \
            --stack-name ${{ env.STACK_NAME }} \
            --capabilities CAPABILITY_IAM \
            --parameter-overrides \
              ApplicationName=${{ env.APPLICATION_NAME }} \
              EnvironmentName=${{ env.APPLICATION_NAME }}-prod \
              SolutionStackName="64bit Amazon Linux 2023 v6.6.3 running Node.js 22" \
            --no-fail-on-empty-changeset

      - name: Get stack outputs
        id: stack-outputs
        run: |
          S3_BUCKET=$(aws cloudformation describe-stacks \
            --stack-name ${{ env.STACK_NAME }} \
            --query 'Stacks[0].Outputs[?OutputKey==`S3Bucket`].OutputValue' \
            --output text)

          APP_NAME=$(aws cloudformation describe-stacks \
            --stack-name ${{ env.STACK_NAME }} \
            --query 'Stacks[0].Outputs[?OutputKey==`ApplicationName`].OutputValue' \
            --output text)

          ENV_NAME=$(aws cloudformation describe-stacks \
            --stack-name ${{ env.STACK_NAME }} \
            --query 'Stacks[0].Outputs[?OutputKey==`EnvironmentName`].OutputValue' \
            --output text)

          echo "s3-bucket=$S3_BUCKET" >> $GITHUB_OUTPUT
          echo "application-name=$APP_NAME" >> $GITHUB_OUTPUT
          echo "environment-name=$ENV_NAME" >> $GITHUB_OUTPUT

  deploy-application:
    needs: [test, deploy-infrastructure]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Download the source files from the test job
      - name: Download source files
        uses: actions/download-artifact@v4
        with:
          name: source-files

      # Verify the source files exist
      - name: Verify source files
        run: |
          echo "Checking if required files exist..."
          ls -la

          if [ -f "package.json" ]; then
            echo "✅ package.json found"
          else
            echo "❌ package.json not found"
            exit 1
          fi

          if [ -f "server.js" ]; then
            echo "✅ server.js found"
          else
            echo "❌ server.js not found"
            exit 1
          fi

          if [ -d "public" ]; then
            echo "✅ public folder found"
            echo "Contents of public:"
            ls -la public/
          else
            echo "❌ public folder not found"
            exit 1
          fi

      - name: Create deployment package for Node.js app
        run: |
          echo "Creating deployment package for Node.js app..."

          # Create deployment package directory
          mkdir deployment-package

          # Copy all necessary files
          cp package.json deployment-package/
          cp package-lock.json deployment-package/
          cp server.js deployment-package/
          cp -r public deployment-package/

          echo "✅ Copied all Node.js app files"

      - name: Create deployment zip
        run: |
          echo "✅ Deployment package structure:"
          ls -la deployment-package/

          # Create zip
          cd deployment-package
          zip -r ../deployment-package.zip .
          cd ..

          echo "✅ Package created:"
          ls -lh deployment-package.zip

      - name: Upload to S3
        run: |
          VERSION_LABEL="v${{ github.run_number }}-$(date +%Y%m%d-%H%M%S)"
          aws s3 cp deployment-package.zip s3://${{ needs.deploy-infrastructure.outputs.s3-bucket }}/${VERSION_LABEL}.zip
          echo "VERSION_LABEL=${VERSION_LABEL}" >> $GITHUB_ENV

      - name: Create application version
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name ${{ needs.deploy-infrastructure.outputs.application-name }} \
            --version-label ${{ env.VERSION_LABEL }} \
            --source-bundle S3Bucket=${{ needs.deploy-infrastructure.outputs.s3-bucket }},S3Key=${{ env.VERSION_LABEL }}.zip \
            --description "Deployed from GitHub Actions - Commit: ${{ github.sha }}"

      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk update-environment \
            --application-name ${{ needs.deploy-infrastructure.outputs.application-name }} \
            --environment-name ${{ needs.deploy-infrastructure.outputs.environment-name }} \
            --version-label ${{ env.VERSION_LABEL }}

      - name: Wait for deployment
        run: |
          echo "Waiting for deployment to complete..."
          aws elasticbeanstalk wait environment-updated \
            --application-name ${{ needs.deploy-infrastructure.outputs.application-name }} \
            --environment-name ${{ needs.deploy-infrastructure.outputs.environment-name }}

      - name: Get application URL
        run: |
          URL=$(aws cloudformation describe-stacks \
            --stack-name ${{ env.STACK_NAME }} \
            --query 'Stacks[0].Outputs[?OutputKey==`ApplicationURL`].OutputValue' \
            --output text)
          echo "Application deployed successfully!"
          echo "URL: $URL"
